export const TOGGLE_MODEL_OPEN = 'TOGGLE_MODEL_OPEN'
export const TOGGLE_MODEL_CLOSE = 'TOGGLE_MODEL_CLOSE'

export const CREATE_EVENT = 'CREATE_EVENT'
export const UPDATE_EVENT = 'UPDATE_EVENT'
export const REMOVE_EVENT = 'REMOVE_EVENT'

export const SET_SELECTED_EVENT = 'SET_SELECTED_EVENT'
