export const GET_MONTH_LIST = 'GET_MONTH_LIST'

export const RESET_MONTH_INDEX = 'RESET_MONTH_INDEX'
export const TOGGLE_MONTH_INDEX = 'TOGGLE_MONTH_INDEX'
export const JUMP_MONTH_INDEX = 'JUMP_MONTH_INDEX'
