export const TOGGLE_MODEL_OPEN = 'TOGGLE_MODEL_OPEN'
export const TOGGLE_MODEL_CLOSE = 'TOGGLE_MODEL_CLOSE'

export const PUBSUB_EVENT_NEW = 'PUBSUB_EVENT_NEW'
export const PUBSUB_SELF_EVENT_NEW = 'PUBSUB_SELF_EVENT_NEW'
export const PUBSUB_EVENT_UPDATE = 'PUBSUB_EVENT_UPDATE'
export const PUBSUB_SELF_EVENT_UPDATE = 'PUBSUB_SELF_EVENT_UPDATE'
export const PUBSUB_EVENT_DELETE = 'PUBSUB_EVENT_DELETE'
export const PUBSUB_SELF_EVENT_DELETE = 'PUBSUB_SELF_EVENT_DELETE'
export const GET_SELF_EVENT_LIST = 'GET_SELF_EVENT_LIST'
export const GET_OTHER_EVENT_LIST = 'GET_OTHER_EVENT_LIST'

export const GET_REPORT_EVENT_LIST = 'GET_REPORT_EVENT_LIST'

export const CREATE_EVENT = 'CREATE_EVENT'
export const UPDATE_EVENT = 'UPDATE_EVENT'
export const REMOVE_EVENT = 'REMOVE_EVENT'

export const SET_SELECTED_EVENT = 'SET_SELECTED_EVENT'
export const CLOSE_SELECTED_EVENT = 'CLOSE_SELECTED_EVENT'

export const TOGGLE_EVENT_LIST_OPEN = 'TOGGLE_EVENT_LIST_OPEN'
export const TOGGLE_EVENT_LIST_CLOSE = 'TOGGLE_EVENT_LIST_CLOSE'

export const ADD_EVENT_FILTER_TYPE = 'ADD_EVENT_FILTER_TYPE'
export const ADD_REPORT_EVENT_FILTER_TYPE = 'ADD_REPORT_EVENT_FILTER_TYPE'

export const SET_EVENT_BOX_POSITION = 'SET_EVENT_BOX_POSITION'

export const RESET_MODEL_OPEN = 'RESET_MODEL_OPEN'
export const RESET_EVENT_DETAIL = 'RESET_EVENT_DETAIL'
