export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST'
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS'
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL'

export const USER_CONTACT_BOOK = 'USER_CONTACT_BOOK'
export const USER_CREATE_CONTACT_BOOK = 'USER_CREATE_CONTACT_BOOK'
export const USER_UPDATE_CONTACT_BOOK = 'USER_UPDATE_CONTACT_BOOK'
export const USER_DELETE_CONTACT_BOOK = 'USER_DELETE_CONTACT_BOOK'

export const USER_INFO = 'USER_INFO'
export const ALL_USER_LIST = 'ALL_USER_LIST'

export const USER_UPDATE_PROFILE = 'USER_UPDATE_PROFILE'

export const USER_SIGNOUT = 'USER_SIGNOUT'

export const USER_CREATE = 'USER_CREATE'
export const USER_DELETE = 'USER_DELETE'
